### ISSUE TITLE
file streaming & json parsing error

### ISSUE THREAD

**Issue by Smellon69** [Jasmisek/znix-panel-loader#3]
I'd use this over keyauth if I could download my file without leaking the URL much like the keyauth download function.

**Comment by Liam5750** [comment]
json_sax.hpp:
![image](https://github.com/Jasmisek/znix-panel-loader/assets/74884194/0a161daa-b98e-4b3d-b47e-b1816709131e)

**Comment by Liam5750** [comment]
You don't gotta do me dirty like that 😭 however I aint dumb enough to use my real name. That still felt real personal.

**Comment by Smellon69** [comment]
Parsing issue was due to not having the link setup correctly.
